In [1]:
%load_ext autoreload
%autoreload 2

In [1]:
import file_classes
from file_classes import SpatialLightModulator, PhotostimulationDevice, StimulationPlane, HolographicPattern, PhotostimulationSeries

In [2]:
from datetime import datetime
from dateutil.tz import tzlocal

from pynwb import NWBFile

nwbfile = NWBFile(
    'my first synthetic recording',
    'EXAMPLE_ID',
    datetime.now(tzlocal()),
)

import numpy as np
slm = SpatialLightModulator(
    name="slm",
    dimensions = [1, 2]
)

dev = PhotostimulationDevice(name="device", description="photostim_device", type='LED', wavelength=320, slm=slm)
imaging_plane = StimulationPlane(name="imaging_plane",  device=dev, opsin='test opsin', pulse_rate=10)

In [3]:
x = np.random.randint(0, 95)
y = np.random.randint(0, 95)

pixel_roi = []
for ix in range(x, x + 5):
    for iy in range(y, y + 5):
        pixel_roi.append((ix, iy, 1))

hp2 = HolographicPattern(name='HolographicPattern', pixel_roi=pixel_roi, stimulation_diameter=5)

In [4]:
from file_classes import PhotostimulationSeries
ser = PhotostimulationSeries(name='hi', field_of_view=1,unit='seconds', format='series', data=[0, 1, 0, 1], holographic_pattern=hp2, stimulus_duration=10, rate=10., stimulation_plane=imaging_plane)

nwbfile.add_stimulus(ser)

In [6]:
from pynwb import NWBHDF5IO

with NWBHDF5IO("basics_tutorial.nwb", "w") as io:
    io.write(nwbfile)

In [7]:
with NWBHDF5IO("basics_tutorial.nwb", "r", load_namespaces=True) as io:
    read_nwbfile = io.read()

In [8]:
from file_classes import StimulusPresentation

sp = StimulusPresentation(name='test_presentation_table', description='abcd')
sp.add_row(label='stim1', start_time=1., end_time=3., stimulus=hp2)
sp.add_row(label='stim2', start_time=4., end_time=6., stimulus=hp2)
df = sp.to_dataframe()
print(df)


    label  start_time  end_time  \
id                                
0   stim1         1.0       3.0   
1   stim2         4.0       6.0   

                                             stimulus  
id                                                     
0   HolographicPattern file_classes.HolographicPat...  
1   HolographicPattern file_classes.HolographicPat...  


In [7]:
from datetime import datetime
from dateutil.tz import tzlocal

from pynwb import NWBFile

nwbfile = NWBFile(
    'my first synthetic recording',
    'EXAMPLE_ID',
    datetime.now(tzlocal()),
)

import numpy as np
slm = SpatialLightModulator(
    name="slm",
    dimensions = [1, 2, 3],#[32, 10],
)

dev = PhotostimulationDevice(name="device", description="photostim_device", type='LED', wavelength=320.)
nwbfile.add_device(dev)

dev = PhotostimulationDevice(name="device1")
nwbfile.add_device(dev)

device1 file_classes.PhotostimulationDevice at 0x140686359114224

In [15]:
# hp = HolographicPattern(name='HolographicPattern', description='HolographicPattern')
import numpy as np

image_mask = np.zeros((100, 100))

# randomly generate example image masks
x = np.random.randint(0, 95)
y = np.random.randint(0, 95)
image_mask[x:x + 5, y:y + 5] = 1
hp = HolographicPattern(name='HolographicPattern',  mask_roi= image_mask)

In [16]:
from file_classes import PhotostimulationSeries
ser = PhotostimulationSeries(name="photosim series", pattern=hp, unit='SIunit',  field_of_view=1, imaging_plane=imaging_plane)

ser.add_interval(10, 20)

nwbfile.add_stimulus(ser)

In [11]:
from file_classes import PhotostimulationSeries
ser = PhotostimulationSeries(name="photosim series", pattern=hp, unit='SIunit',  field_of_view=1, format='series', data=[0, 1, 0], rate=10., imaging_plane=imaging_plane)

NameError: name 'hp' is not defined

In [12]:
x = np.random.randint(0, 95)
y = np.random.randint(0, 95)

pixel_roi = []
for ix in range(x, x + 5):
    for iy in range(y, y + 5):
        pixel_roi.append((ix, iy, 1))

hp2 = HolographicPattern(name='HolographicPattern', pixel_roi=pixel_roi, stimulation_diameter=5, dimension=[100, 100])
ser = PhotostimulationSeries(name="photosim series2", pattern=hp2, unit='SIunit',  imaging_plane=imaging_plane)
# nwbfile.add_stimulus(ser)

In [23]:
from pynwb import NWBHDF5IO

f_name = 'holographic_photosim_example.nwb'
io = NWBHDF5IO(f_name, mode='w')
io.write(slm)
io.close()

In [5]:
with NWBHDF5IO("basics_tutorial.nwb", "r", load_namespaces=True) as io:
    read_nwbfile = io.read()
    # print(read_nwbfile.pixel_roi[:])
    # print(read_nwbfile.stimulation_diameter)

[[56  4  1]
 [56  5  1]
 [56  6  1]
 [56  7  1]
 [56  8  1]
 [57  4  1]
 [57  5  1]
 [57  6  1]
 [57  7  1]
 [57  8  1]
 [58  4  1]
 [58  5  1]
 [58  6  1]
 [58  7  1]
 [58  8  1]
 [59  4  1]
 [59  5  1]
 [59  6  1]
 [59  7  1]
 [59  8  1]
 [60  4  1]
 [60  5  1]
 [60  6  1]
 [60  7  1]
 [60  8  1]]
5


In [20]:
from pynwb import NWBHDF5IO
dev = PhotostimulationDevice(name="device", description="photostim_device", type='LED', wavelength=320., slm=slm)

dev = PhotostimulationDevice(name="device", description="photostim_device", type='LED')

dev = PhotostimulationDevice(name="device", description="photostim_device", type='LED', wavelength=320., slm=slm)

f = "basics_tutorial.nwb"
io = NWBHDF5IO(f, 'w')
io.write(slm)
io.write(imaging_plane.device)
io.write(imaging_plane)
io.close()

/Users/harriscaw/opt/anaconda3/envs/NWB/lib/python3.10/site-packages/hdmf/build/objectmapper.py:660: MissingRequiredBuildWarning: ImagingPlane 'imaging_plane' is missing required value for attribute 'pulse_rate'.
  warnings.warn(msg, MissingRequiredBuildWarning)
/Users/harriscaw/opt/anaconda3/envs/NWB/lib/python3.10/site-packages/hdmf/build/objectmapper.py:660: MissingRequiredBuildWarning: ImagingPlane 'imaging_plane' is missing required value for attribute 'power'.
  warnings.warn(msg, MissingRequiredBuildWarning)
/Users/harriscaw/opt/anaconda3/envs/NWB/lib/python3.10/site-packages/hdmf/build/objectmapper.py:660: MissingRequiredBuildWarning: ImagingPlane 'imaging_plane' is missing required value for attribute 'peak_pulse_power'.
  warnings.warn(msg, MissingRequiredBuildWarning)
/Users/harriscaw/opt/anaconda3/envs/NWB/lib/python3.10/site-packages/hdmf/build/objectmapper.py:660: MissingRequiredBuildWarning: ImagingPlane 'imaging_plane' is missing required value for attribute 'opsin'.
  

In [11]:
io.close()

In [10]:
from pynwb import load_namespaces, get_class, NWBHDF5IO, NWBFile

ns_path = "test.namespace.yaml"
load_namespaces(ns_path)
PS = get_class("PhotostimulationSeries", "test")

ser = PS(name='hi', field_of_view=1,unit='seconds', format='series', data=[0, 1, 0], stimulation_plane=imaging_plane, stimulus_duration=10, rate=10.)


TypeError: PhotostimulationSeries.__init__: incorrect type for 'stimulation_plane' (got 'PhotostimulationDevice', expected 'StimulationPlane')

In [8]:
dir(ps)

['DEFAULT_CONVERSION',
 'DEFAULT_DATA',
 'DEFAULT_OFFSET',
 'DEFAULT_RESOLUTION',
 'DEFAULT_UNIT',
 '_AbstractContainer__fieldsconf',
 '_AbstractContainer__gather_fields',
 '_Container__smart_str',
 '_Container__smart_str_dict',
 '_Container__smart_str_list',
 '_TimeSeries__add_link',
 '_TimeSeries__get_links',
 '_TimeSeries__time_unit',
 '__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__fields__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__nwbfields__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_field_spec',
 '_check_field_spec_keys',
 '_check_time_series_dimension',
 '_data_type_attr',
 '_experimental',
 '_fieldsname',
 '_get_fields',
 '_getter',
 '_pconf_allowed_keys',
 '_remove_child',
 '_set_fields